### ISSUE TITLE
Description and Labels should be Optional

### ISSUE THREAD

**Issue by tpoindessous** [free/jiralert#10]
Hi

I work with a customer which has disabled Description and Labels in his own Jira configuration.

Could you, please, make this two fields optional ?

My team will try to submit a PR in the next weeks 😄 

Thanks !

**Comment by free** [comment]
The whole idea behind JIRAlert is to use labels to identify the issue corresponding to a specific alert (to reopen it if it already exists). If you disable label creation, then all that's left is a webhook that creates new JIRA issues for every single Alertmanager API call (including every time the same alert is repeated).

You could, in theory, use a different field to store this unique identifier, but that may make it way more complex to configure in the average case (as you'd always need to say which field sure the ID, and maybe whether it's a prefix or whatever).

I believe it would be way easier to convince your customer to enable labels.

As for the description, you could conditionally disable that from JIRAlert, (with code changes) but how useful would such an issue be?

**Comment by tpoindessous** [comment]
Thanks for your answer !

I will look with my coworkers and I will come back with answers.

I think that my customer has made a custom field for Description :( ( don't
ask why :) ).

Have a nice day !



Le mar. 10 juil. 2018 à 19:41, Alin Sinpalean <notifications@github.com> a
écrit :
