### ISSUE TITLE
New JIRA ticket for every new alert

### ISSUE THREAD

**Issue by ManCon** [free/jiralert#12]
Hi

I have installed jiralert in my test environment and it works fine.

But I am a little bit confused.
Fore example I have configured a Prometheus alert for disk usage 90% full.
3 servers has a disk who is fuller than the configured 90%.
So I am expecting 3 different alerts. 
For every server one separate alert. Because the problem has to be fixed on 3 servers!
But I see in the JIRA only one ticket with 3 comments for the 3 servers.

In my understanding is every alert a own task or a own "ToDo" or "ToCheck" and to "Solve".
So I think it would be better to open for every alert a own JIRA ticket.
Even if the alert is solved and he appeared later again is it in my understanding a new JIRA ticket.
Because he has to be solved again. It is also a new task for the supporter and not a reopened ticket.  

How can I configure my system so that I get a new JIRA ticket for every separate alert? 

Thanks in advance ;-)

**Comment by charlspjohn** [comment]
> Hi
> 
> I have installed jiralert in my test environment and it works fine.
> 
> But I am a little bit confused.
> Fore example I have configured a Prometheus alert for disk usage 90% full.
> 3 servers has a disk who is fuller than the configured 90%.
> So I am expecting 3 different alerts.
> For every server one separate alert. Because the problem has to be fixed on 3 servers!
> But I see in the JIRA only one ticket with 3 comments for the 3 servers.
> 
> In my understanding is every alert a own task or a own "ToDo" or "ToCheck" and to "Solve".
> So I think it would be better to open for every alert a own JIRA ticket.
> Even if the alert is solved and he appeared later again is it in my understanding a new JIRA ticket.
> Because he has to be solved again. It is also a new task for the supporter and not a reopened ticket.
> 
> How can I configure my system so that I get a new JIRA ticket for every separate alert?
> 
> Thanks in advance ;-)

I'm not sure whether my suggestion is possible in Jira or not. But I have a similar requirement like yours. I am thinking of creating a workflow which removes the 'grouplabel' label from the alert ticket when it is going to 'Resolved' resolution. Is it somehow possible ?

--
Thanks,
Charls

**Comment by ManCon** [comment]
Hello Charls

I don't have found a solution to disable the grouplabel functionality.
But we use the grouped alerts and it works fine for our requirements.

Best regards
Manfred

Am Di., 22. Jan. 2019 um 14:33 Uhr schrieb Charls P John <
notifications@github.com>:

**Comment by bwplotka** [comment]
Looks to me like this is resolved (: 

Also tuning `Reopen` (put to 0) will completely disable the reopening.
