### ISSUE TITLE
nil pointer dereference error in handleJiraError

### ISSUE THREAD

**Issue by csupi** [free/jiralert#16]
I receive a nil pointer dereference error in notify.go:195 (handleJiraError). This error hides the real issue.

> runtime error: invalid memory address or nil pointer dereference
...
> github.com/anchorfree/jira-alerter.handleJiraError(0x0, 0xb1b180, 0xc4203a16e0, 0xc42017f090, 0x0, 0x0)
> 	/go/src/github.com/anchorfree/jira-alerter/notify.go:195 +0x93
> github.com/anchorfree/jira-alerter.(*Receiver).search(0xc420183780, 0xc420184548, 0x2, 0xc420183ce0, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
> 	/go/src/github.com/anchorfree/jira-alerter/notify.go:149 +0x817
> github.com/anchorfree/jira-alerter.(*Receiver).Notify(0xc420183780, 0xc420192c00, 0xc420183780, 0x0, 0x0)
> 	/go/src/github.com/anchorfree/jira-alerter/notify.go:61 +0x1db
> main.main.func1.1(0xb20a00, 0xc420364000, 0xc420199200)
> 	/go/src/github.com/anchorfree/jira-alerter/cmd/jiralert/main.go:102 +0x422

**Comment by bwplotka** [comment]
Is it still valid? I think code changed bit after a half a year - let us know if you are repro this (: We will reopen this then.
