### ISSUE TITLE
Unable to create new jira ticket.

### ISSUE THREAD

**Issue by sravankumar-n** [free/jiralert#21]
Hi 

Unable to create new ticket in jira .

Getting below error

notify.go:84] No issue matching [] found, creating new issue
 notify.go:184] create: issue={    0xc420083680 <nil>}
 notify.go:195] handleJiraError: err=Request failed. Please analyze the request body for more details. Status code: 400, req=http://jira:8080/rest/api/2/issue/
notify.go:107] Issue created: key= ID=
main.go:192] 500 Internal Server Error: err=JIRA request http://jira:8080/rest/api/2/issue/ returned status 400 , body "{\"errorMessages\":[],\"errors\":{\"project\":\"project is required\"}}" receiver="jira" groupLabels=map[alertname:InstanceDown]

can any one help me out. Thanks in advance.

**Comment by bwplotka** [comment]
Hey (: Are you sure that for your configuration `Project` field is filled?

**Comment by devopszone** [comment]
Hi , 
In the Configuration File i have filled Project filed with "Test-Alert"  this is not working.
Later i tried with KEY of the Project(TES)  with out any special characters. 

Now its is working fine.
