### ISSUE TITLE
Unable to create JIRA Issue

### ISSUE THREAD

**Issue by jartitodebuscarusuario** [free/jiralert#39]
Hi!

I'm working on integrating prometheus alertmanager with JIRA. I have a simple config copy of that in the git repo. This is the log from jiralert when receiving alerts:

`I0710 13:09:55.671240    5085 main.go:58] Handling /alert webhook request`
`I0710 13:09:55.671433    5085 main.go:73] Matched receiver: "deadmansswitch"`
`I0710 13:09:55.671461    5085 template.go:48] Executing template "TEST"...`
`I0710 13:09:55.671469    5085 template.go:50]   returning unchanged.`
`I0710 13:09:55.671480    5085 notify.go:179] search: query=project="TEST" and labels="ALERT}" order by resolutiondate desc options=&{StartAt:0 MaxResults:2 Expand: Fields:[summary status resolution resolutiondate] ValidateQuery:}`
`I0710 13:09:55.673406    5085 notify.go:233] handleJiraError: api=Issue.Search, url=https://jiraurl/rest/api/2/search?jql=project%3D%22TEST%22+and+labels%3D%22ALERT%7D%22+order+by+resolutiondate+desc&startAt=0&maxResults=2&expand=&fields=summary,status,resolution,resolutiondate&validateQuery=, err=Request failed. Please analyze the request body for more details. Status code: 403: Could not parse JSON: unexpected end of JSON input`
`E0710 13:09:55.673470    5085 main.go:133] 500 Internal Server Error: err=JIRA request [](https://jiraurl/rest/api/2/search?jql=project%3D%22TEST%22+and+labels%3D%22ALERT%7D%22+order+by+resolutiondate+desc&startAt=0&maxResults=2&expand=&fields=summary,status,resolution,resolutiondate&validateQuery=) returned status 403 , body "" receiver="deadmansswitch" groupLabels=map[]`

I can do the query in the log with curl with no errors:

`curl -u user:pass -H "Content-type: application/json" "https://jiraurl/rest/api/2/search?jql=proyecto%3D%22TEST%22+and+labels%3D%22ALERT%7D%22+order+by+resolutiondate+desc&startAt=0&maxResults=2&expand=&fields=summary,status,resolution,resolutiondate&validateQuery="`

`{"startAt":0,"maxResults":2,"total":0,"issues":[]}`

Also, I can create JIRA issues using the API, as described in [https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/](https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/)

Any ideas about what I'm doing wrong?

Thanks in advance

**Comment by Annamdinesh** [comment]
hi @jartitodebuscarusuario.
Have you done this Integration? I'm facing same issue
