### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by charlspjohn** [free/jiralert#4]
When I run the Jiralert with a https JIRA api url, getting the below error

> 2018/04/12

 09:09:51 http: panic serving 127.0.0.1:46502: runtime error: invalid memory address or nil pointer dereference
goroutine 956 [running]:
net/http.(*conn).serve.func1(0xc4200abcc0)
        /usr/lib/go-1.9/src/net/http/server.go:1697 +0xd0
panic(0x84d380, 0xb578d0)
        /usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
github.com/free/jiralert.handleJiraError(0x0, 0xb25fa0, 0xc42016fad0, 0xc4202ec840, 0x0, 0x0)
        /home/alin/go/src/github.com/free/jiralert/notify.go:162 +0x93
github.com/free/jiralert.(*Receiver).search(0xc420476bc0, 0xc4201901d8, 0x3, 0xc420168510, 0x2c, 0xc4201901d8, 0x3, 0x31, 0x16)
        /home/alin/go/src/github.com/free/jiralert/notify.go:116 +0x5df
github.com/free/jiralert.(*Receiver).Notify(0xc420476bc0, 0xc420195020, 0xc420476bc0, 0x0, 0x0)
        /home/alin/go/src/github.com/free/jiralert/notify.go:44 +0x107
main.main.func1(0xb2aaa0, 0xc42026c460, 0xc42048c200)
        /home/alin/go/src/github.com/free/jiralert/cmd/jiralert/main.go:86 +0x3a3
net/http.HandlerFunc.ServeHTTP(0xc42010b880, 0xb2aaa0, 0xc42026c460, 0xc42048c200)
        /usr/lib/go-1.9/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xb663e0, 0xb2aaa0, 0xc42026c460, 0xc42048c200)
        /usr/lib/go-1.9/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc42020e0d0, 0xb2aaa0, 0xc42026c460, 0xc42048c200)
        /usr/lib/go-1.9/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4200abcc0, 0xb2b3e0, 0xc4202ec680)
        /usr/lib/go-1.9/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/lib/go-1.9/src/net/http/server.go:2720 +0x288

> 

When changing api_url to http, then there wont be any error.

**Comment by free** [comment]
The commit above should have fixed this issue. I've also made a new release, let me know if it works for you: https://github.com/free/jiralert/releases/tag/0.5

The problem seems to stem from a logging statement triggered upon the failure of a JIRA request before it is even sent to JIRA (probably something to do with invalid URLs). You should now see the root cause logged instead of the segfault.

Cheers,
Alin.

**Comment by charlspjohn** [comment]
Thank you !, I got the error message now. Opened another issue for that #5
