### ISSUE TITLE
Another memory error

### ISSUE THREAD

**Issue by charlspjohn** [free/jiralert#6]
Hi,
 I managed to integrate JIRAlert with jira instance and it is working as expected. However I'm getting the below error:

2018/05/04 13:27:19 http: panic serving 127.0.0.1:41092: runtime error: invalid memory address or nil pointer dereference
goroutine 364 [running]:
net/http.(*conn).serve.func1(0xc4200e2e60)
        /usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0x837720, 0xb4ac30)
        /usr/lib/go-1.10/src/runtime/panic.go:505 +0x229
github.com/free/jiralert.(*Receiver).Notify(0xc42040cde0, 0xc42009acc0, 0xc42040cde0, 0x0, 0x0)
        /home/alin/go/src/github.com/free/jiralert/notify.go:56 +0xfc5
main.main.func1(0x9176e0, 0xc420246380, 0xc4201cb000)
        /home/alin/go/src/github.com/free/jiralert/cmd/jiralert/main.go:86 +0x386
net/http.HandlerFunc.ServeHTTP(0xc420152f40, 0x9176e0, 0xc420246380, 0xc4201cb000)
        /usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xb5ab80, 0x9176e0, 0xc420246380, 0xc4201cb000)
        /usr/lib/go-1.10/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4200add40, 0x9176e0, 0xc420246380, 0xc4201cb000)
        /usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4200e2e60, 0x917c20, 0xc4200bad00)
        /usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/lib/go-1.10/src/net/http/server.go:2795 +0x27b

**Comment by ZiggyMaes** [comment]
Hi

We are experiencing the same issue mentioned above. Here's the stack trace:

``I0516 16:31:54.206682       1 main.go:44] Starting JIRAlert version 0.5
I0516 16:31:54.213295       1 main.go:110] Listening on :9097
^[[A^[[B2018/05/16 16:34:31 http: panic serving x.x.x.x.:56692: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc420242000)
	/usr/lib/go-1.10/src/net/http/server.go:1726 +0xd0
panic(0x837720, 0xb4ac30)
	/usr/lib/go-1.10/src/runtime/panic.go:505 +0x229
github.com/free/jiralert.(*Receiver).Notify(0xc42014e1a0, 0xc42014c120, 0xc42014e1a0, 0x0, 0x0)
	/home/alin/go/src/github.com/free/jiralert/notify.go:56 +0xfc5
main.main.func1(0x9176e0, 0xc42025c000, 0xc420250000)
	/home/alin/go/src/github.com/free/jiralert/cmd/jiralert/main.go:86 +0x386
net/http.HandlerFunc.ServeHTTP(0xc420135d40, 0x9176e0, 0xc42025c000, 0xc420250000)
	/usr/lib/go-1.10/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xb5ab80, 0x9176e0, 0xc42025c000, 0xc420250000)
	/usr/lib/go-1.10/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc42009dee0, 0x9176e0, 0xc42025c000, 0xc420250000)
	/usr/lib/go-1.10/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420242000, 0x917c20, 0xc420248040)
	/usr/lib/go-1.10/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/lib/go-1.10/src/net/http/server.go:2795 +0x27b``

**Comment by free** [comment]
Hmm... Looks like an issue was already created, but has no resolution. Not sure whether that's to be expected from a newly created issue, and why I didn't run into it while testing. (Is there such a thing as a default resolution and if you don't set it then it's empty?)

Could any of you guys please double-check how your issue looks like? (In terms of does it have a resolution/state?) The offending line of code is https://github.com/free/jiralert/blob/0.5/notify.go#L56

**Comment by ZiggyMaes** [comment]
Hi @free, thank you for your quick answer. I can indeed reproduce this error for issues that have status Done but no immediate resolution (unresolved)

https://gyazo.com/69ddfc689e3ce520ad88267b883b0d86

**Comment by free** [comment]
[Didn't want to close this, GitHub must have thought "Attempt to fix" is the same as "fix". Reopening]

I've added a `issue.Fields.Resolution != nil` check to the offending line. Let me know if that does anything for you guys.

**Comment by charlspjohn** [comment]
Issue no more happening
